name: OinkUtils
author: ByteKangaroo
main: com.oinkcraft.oinkutils.Main
version: 1.3
api-version: 1.13
description: Utilities for the main Oinkcraft server
softdepend:
  - Multiverse-Core
commands:
  oinkutils:
    usage: /<command>
    description: Base OinkUtils command.
  chatcolorchange:
    usage: /<command>
    description: Allows a player to change the color of their chat
  modtools:
    aliases: [mtools]
    description: The base ModTool command to enable all your ModTool needs!
    usage: /mtools help
  sneeze:
    aliases: [clearentities]
    description: The sneeze command to get rid of entities - within ModTools package
    usage: /sneeze <radius>
  submit:
    description: Submit for builder, redstone, or parkour
    usage: /submit
  vote:
    description: Vote command to list links
    usage: /vote
permissions:
  oinkutils.admin:
    description: No need for a command yet, so...
  oinkutils.colorchange:
    description: Allows a player to change the color of their chat
  modtools.use:
    description: Allows a player, or rank, to use the modtools command.
  oinkutils.mobspawn:
    description: Allows players to place mob spawn eggs or not.
  oinkutils.advbuilder.build:
    description: Allows players to use creative gamemode and build in advanced builder (not turn into spectator)
  oinkutils.redstone.build:
    description: Allows players to use creative gamemode and build in redstone world (not turn into spectator)